### ISSUE TITLE
Returning Negative Values

### ISSUE THREAD

**Issue by shotah** [dcrystalj/hx711py3#6]
Hello dcrystalj,

This library is awesome, and I've been trying to follow it closely to get my project to return clean values. Everything seems to be working great. I was just going to use the absolute values, but I was hoping you may know why this is returning negative values for me? Thanks for taking the time.

Here is the load cells I have wired to my Raspberry Pi: 
https://www.amazon.com/Half-bridge-Weighting-Sensor-Weight-Geekstory/dp/B079FTXR7Y/ref=asc_df_B079FTXR7Y/?tag=hyprod-20&linkCode=df0&hvadid=241927124583&hvpos=1o2&hvnetw=g&hvrand=14969056602392915352&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9033305&hvtargid=pla-426277064612&psc=1

Thanks again!
Christopher

**Comment by dcrystalj** [comment]
Hm. This kind of sensors are the cheapest and the worst. I read few blogs about it back in time and just decided to spend more money on better sensor before ordering anyhting.
Make sure to connect your sensor as [wheatstone bridge](https://en.wikipedia.org/wiki/Wheatstone_bridge) to maximally reduce sensor errors. Note that my sensor on the repo picture have this bridge implemented already (at least they said so)

Many things can go wrong on this kind of sensors. Thats why I was trying to eliminate them and make a lot of averaging after it to have better readings. 

Dropping negative values seems the best choice to me as well.

Note that this sensors can be bought on [aliexpress](https://www.aliexpress.com/item/4Pcs-50kg-Human-Scale-Load-Cell-Weight-Sensors-HX711-Module-Body-Load-Cell-Weighing-Sensor-Pressure/32966015097.html?ws_ab_test=searchweb0_0,searchweb201602_3_10065_10068_10890_319_10546_317_10548_10696_453_10084_454_10083_10618_431_10304_10307_10820_537_536_10059_10884_10887_100031_321_322_10103-10890,searchweb201603_6,ppcSwitch_0&algo_expid=78c629f3-9685-4066-ba4d-57d7cca11094-26&algo_pvid=78c629f3-9685-4066-ba4d-57d7cca11094) for less price. My sensor was ~ 15$, because I needed from it to take 150kg load.

**Comment by shotah** [comment]
Yep with the absolute value and thanks for the update. I do have them in a wheatstone bridge and they seem to be fine, other than the micro fluctuations with seem to be able to be rounded out. I did find when I applied pressure the inverse direction the numbers went positive. That being said, I have what I need. Thanks for this!
